### ISSUE TITLE
Make the provider pattern functionality for user. schedule and sleep not so janky

### ISSUE THREAD

**Issue by scarcheek** [Discord-Radio-Devs/PolySleeper#10]
Like bro what is this 
We need to use Consumers I think to solve this issue
Check the official [Flutter Docs](https://docs.flutter.dev/development/data-and-backend/state-mgmt/simple) for help

**Comment by scarcheek** [comment]
YOOOOOOOOOOOOOOOOOOOOOOO

**Comment by Lancear** [comment]
weeeeeeeeeee did iiiiiiiiiiiiiiiiiiiiiit
